name=MiP Power Up
version=2.1.0
author=Samuel Trassare <tiogaplanet@users.noreply.github.com>
maintainer=Samuel Trassare <tiogaplanet@users.noreply.github.com>
sentence=Control WowWee MiP from ESP8266 and Arduino AVR boards.
paragraph=This library abstracts MiP's low-level binary UART protocol into an easy-to-use C++ interface. Use it with the MiP Power Up adapter boards to seamlessly control his motion, sensors, sound, and LEDs, while unlocking powerful WiFi and OTA networking features on supported microcontrollers.
category=Device Control
url=https://github.com/Tiogaplanet/MiP_Power_Up_lib
architectures=esp8266,avr,*
includes=MiP_Power_Up.h
